### PR TITLE
Remove handling for adding product to cart manually since core alread…

### LINKED ISSUE #408: Single Product:  Quantity being duplicated due to multiple AJAX calls
Problem:  When you add a product from the single-product page, the quantity is doubled in PayPal.

1. Go to a Single Product
2. Make sure your cart is empty
3. Click "Check out with PayPal"

I add a $5 product:
screen shot 2018-05-02 at 12 45 25 pm
PayPal shows me this:
screen shot 2018-05-02 at 12 47 57 pm

Reason:
There are 2 AJAX calls going on here.  One of them is added here:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/985bb5404e8524905c4c04fdf2c505430bf8c7c4/includes/class-wc-gateway-ppec-cart-handler.php#L29

The other one is being fired off in JS here:
https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/master/assets/js/wc-gateway-ppec-generate-cart.js#L81-L87

If you remove one of those two AJAX calls, the problem is fixed.

### PR DESCRIPTION
**Pull request by bor0**
…y does it for us

Fixes #408.

### CODE REVIEW

**Comment by roykho** [comment]
This does not work for me. When I click the button, I am just redirected to empty cart page

**Comment by bor0** [comment]
@roykho weird, I knew there was a reason I had added that. What WC version are you using? For some reason, it works on my local tests.

**Comment by roykho** [comment]
WC master. Logged in with empty cart to start. Go to product page and click PPEC button. Redirected to empty cart page. Switched back to PPEC master, everything works again but of course with 2x quantity.

**Comment by bor0** [comment]
@roykho ok I think a good bandaid for that is to empty the cart before express checkout. Can you please give this latest PR a try? Thanks!

**Pull request merged**
