### PR TITLE
Set txnData regardless of action type

### LINKED ISSUE #245: Cannot process refunds on "authorize" transactions
Authorize transactions never get their _woo_pp_txnData meta updated after capture action.

So process_refund() see's a blank array() for _woo_pp_txnData ($txn_data['refundable_txns']) and returns the error: "Refund Error: All transactions have been fully refunded. There is no amount left to refund"

FYI, I test this with a base theme and newest version of WordPress, WooCommerce and PayPal Express checkout (including the repo's master branch). Same issue happens.

Refunds work with "sale", but still get the same issue with "authorize".

Is the issue in this code logic?

Line 599 (class-wc-gateway-ppec-checkout-handler.php):

### PR DESCRIPTION
**Pull request by bor0**
Fixes #245.

### CODE REVIEW

**Comment by bor0** [comment]
@creativeround can you please confirm this PR fixes the issue for you? Thanks!

**Comment by gedex** [comment]
@bor0 it doesn't work for me.  The `_woo_pp_txnData` is successfully stored in order meta, but transaction ID should also be saved in `_transaction_id` meta. Apparently capture is not working too:

```
(
    [ADDRESSOWNER] => PayPal
    [ADDRESSSTATUS] => None
    [TIMESTAMP] => 2017-06-06T09:00:40Z
    [CORRELATIONID] => 1adead0a675e5
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 25237094
    [L_ERRORCODE0] => 10011
    [L_SHORTMESSAGE0] => Invalid transaction id value
    [L_LONGMESSAGE0] => A transaction id is required
    [L_SEVERITYCODE0] => Error
    [PENDINGREASON] => None
    [REASONCODE] => None
    [L_TAXABLE0] => false
)
```

**Comment by bor0** [comment]
@gedex that's weird because it should be set [here](https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/41e7fb6df701cf1e1fc2d017e461e2df8a62089b/includes/class-wc-gateway-ppec-checkout-handler.php#L815). Could you check the DB to see if that order has that meta populated?

**Comment by bor0** [comment]
I think I found the issue. `_transaction_id` is set as an internal key in `WC_Order` so there are probably issues around `$order->update_meta_data`. I think if we use `update_post_meta` it should work. Updated the PR, another round please @gedex.

**Comment by gedex** [comment]
@bor0 transaction ID is now saved properly in order meta. I can see the transaction link in edit order screen:

screen shot 2017-06-06 at 5 48 21 pm

However, it seems the capture action is not using that meta properly. This is not related to your PR. but seems regression after WC 3.0 compat. When I do capture via edit order screen:


screen shot 2017-06-06 at 6 16 10 pm

I got:

```
(
    [ADDRESSOWNER] => PayPal
    [ADDRESSSTATUS] => None
    [TIMESTAMP] => 2017-06-06T10:47:55Z
    [CORRELATIONID] => adaec79edafbf
    [ACK] => Failure
    [VERSION] => 120.0
    [BUILD] => 25237094
    [L_ERRORCODE0] => 10011
    [L_SHORTMESSAGE0] => Invalid transaction id value
    [L_LONGMESSAGE0] => A transaction id is required
    [L_SEVERITYCODE0] => Error
    [PENDINGREASON] => None
    [REASONCODE] => None
    [L_TAXABLE0] => false
)
```

**Comment by bor0** [comment]
@gedex good catch! I tested it locally and the same issue is with reading. I updated the code again.

**Comment by bor0** [comment]
We need to use `get_transaction_id` and `set_transaction_id` instead of updating the post meta directly, but for now since this was tested and is working fine we can go with this.

**Pull request merged**
