### PR TITLE
Add logic to enable/disable button for variations form

### LINKED ISSUE #294: Checkout on single product available before variations are chosen
User in [this forum thread](https://wordpress.org/support/topic/paypal-express-product-page-not-working-with-variations/) brought up this issue. 

If **Checkout on Single Product** is enabled, then the checkout button is available on single products before required options, such as variation drop downs, are selected. 

### Steps to reproduce

1. Enable **Checkout on Single Product**
1. View a variable product that *does not* have a default selection
1. Checkout button will be available and clickable ❌ 

Image Link: http://cld.wthms.co/6Jjbax

### PR DESCRIPTION
**Pull request by bor0**
Fixes #294.

### CODE REVIEW

**Comment by gedex** [comment]
@bor0 

Works fine on Firefox, but doesn't work in Chrome Version 59.0.3071.115 (Official Build) (64-bit). Here's the recording of it:

test-294

**Comment by gedex** [comment]
@bor0 Apparently the issue in Chrome only happens when I logged in.

**Comment by gedex** [comment]
@bor0 Updated with your latest commit and works fine now.

**Comment by jessepearson** [comment]
Works for me 👍 


Image Link: http://cld.wthms.co/Dh27t

**Pull request merged**
