### PR TITLE
Update bundle.pem

### PR DESCRIPTION
**Pull request by meek2100**
###Tickets:
My Support Post: 
https://wordpress.org/support/topic/paypal-not-working-curl-error-60-peers-certificate-issuer/#post-13500869

Other Posts That Sound Similar:
https://wordpress.org/support/topic/paypal-error-3-an-error-message-but-credentials-are-correct/
https://wordpress.org/support/topic/the-api-credentials-you-provided-are-not-valid-2/
https://wordpress.org/support/topic/an-error-occurred-while-trying-to-validate-your-api-credentials/

### Description:
The certificates in this chain for api-3t.sandbox.paypal.com are outdated & expired. I've updated this with the new certificate chain issued by DigiCert that is used by PayPal (https://www.paypal.com/us/smarthelp/article/where-can-i-find-paypal-ssl-server-certificates-ts1510).

### Steps to test:
1. Update bundle.pem
2. Authenticate Paypal
3. Enable Paypal
4. Checkout successfully.

### Documentation
No

### Changelog entry
Updated bundle.pem

### CODE REVIEW

**Comment by meek2100** [comment]
For verification of the .pem bundle, it can be verified here: https://tools.keycdn.com/ssl  or with other certificate verification tools.

**Comment by starkmatt** [comment]
Hey man,
Thanks for much for this.
I followed your Post from Wordpress to here.

Mind if we connect, so you can walk me through replacing the cert ?
Just had a crack but I'm just a little hesitant !

Thanks

**Comment by starkmatt** [comment]
Hey man,
Thanks so much for this, I followed your post from Wordpress to here and I've tried it in my own environment.
Can confirm that this works and fixes the issue 

```"PayPal error (3): An error (3) occurred while processing your PayPal payment. Please contact the store owner for assistance."```

And

```An error occurred while trying to validate your API credentials. Unable to verify that your API credentials are correct.```

**Comment by mattallan** [comment]
Thanks @meek2100, I've confirmed the new certificates being updated here are correct :+1:

 - PayPal Certs https://www.paypal.com/us/smarthelp/article/where-can-i-find-paypal-ssl-server-certificates-ts1510
   - `api-3t.sandbox.paypal.com`
 - DigiCert Intermediates: https://www.digicert.com/kb/digicert-root-certificates.htm#intermediates
   - `DigiCert SHA2 High Assurance Server CA `
   - `DigiCert High Assurance EV Root CA`

**Pull request merged**
