### PR TITLE
Updated supported locales

### PR DESCRIPTION
**Pull request by NZI**
Added New Zealand as a supported locale

### CODE REVIEW

**Comment by allendav** [comment]
Are you certain `en_NZ` is supported?

e.g. I looked at https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/#supported-locales

which refers to

https://developer.paypal.com/docs/integration/direct/rest/locale-codes/#supported-locale-codes

and for New Zealand, it cites `en_US`, `fr_XC`, `es_XC` and `zh_XC` as the only supported locale codes. `en_NZ` does not appear in the list for any country.

**Comment by NZI** [comment]
That's weird because I put that locale into the code for one of my sites and paypal recognized it and the default country was set to "New Zealand", any reason it wouldn't be supported?

**Comment by dechov** [comment]
For what it's worth, I do see it listed in the Javascript SDK doc [[#](https://developer.paypal.com/docs/checkout/reference/customize-sdk/#locale)], which is what the newer Smart Payment Buttons integration uses (see top of [this doc](https://developer.paypal.com/docs/archive/checkout/how-to/customize-button/)).

**Comment by NZI** [comment]
https://developer.paypal.com/docs/archive/checkout/reference/supported-locales/

`en_NZ` is now on the supported list of locales. Can this be merged? I can push the other locales if need be

**Comment by james-allan** [comment]
closing in favour of #658

**Pull request closed without merging**
