### PR TITLE
Use Lambda team's standard github README and templates

### PR DESCRIPTION
**Pull request by chickenn00dle**
### Description

PPEC currently has no README. This PR adds one following the standard from our other repos.

This also updates the PR template to include a changelog entry.

### CODE REVIEW

**Comment by LCmry** [comment]
Looks good @chickenn00dle , one small change is that the `main` branch is now `trunk` 😅

**Comment by chickenn00dle** [comment]
Ah, good catch @LCmry!

I updated the README in https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/794/commits/52d3a8fafa8241c2acd47408ebf87606e7d4fce2

**Comment by LCmry** [comment]
One more Q @chickenn00dle , where is the Changelog entry being drawn from. AFAIK it's not in our other repos, at least unless we inherited it. I know this is a practice other teams do, I wonder what the pros and cons are and if it will be helpful at release time?

**Comment by chickenn00dle** [comment]
@LCmry This was discussed when we standardized the Square templates:
https://github.com/woocommerce/woocommerce-square/pull/470

You can find specific details in this comment:
https://github.com/woocommerce/woocommerce-square/pull/470#discussion_r455470463

I believe there may have also been a Slack discussion around this, but am not finding it atm.

Let me know if this doesn't answer your question!

**Comment by LCmry** [comment]
Gotcha, thanks for the trail @chickenn00dle! LGTM 👍

**Pull request merged**
